version: "3.9"

services:
  web:
    build: .
    container_name: microservicio-usuarios
    ports:
      - "8000:8000"
    env_file:
      - .env #  aquí le pasamos todas las variables desde tu archivo .env
    volumes:
      - .:/app # monta tu código local dentro del contenedor (útil en desarrollo)
    command: >
      python manage.py runserver 0.0.0.0:8000
